# ============================================
# CONFIGURACIÓN DEL MICROSERVICIO
# ============================================
spring.application.name=ms-catalogo
server.port=8081

# ============================================
# CONFIGURACIÓN DE BASE DE DATOS - MySQL
# ============================================
spring.datasource.url=jdbc:mysql://localhost:3306/mm_catalogo?useSSL=false&serverTimezone=America/Santiago&allowPublicKeyRetrieval=true
spring.datasource.username=root
spring.datasource.password=
spring.datasource.driver-class-name=com.mysql.cj.jdbc.Driver

# ============================================
# CONFIGURACIÓN DE JPA + HIBERNATE
# ============================================
spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true
spring.jpa.properties.hibernate.format_sql=true
spring.jpa.open-in-view=false

# ============================================
# CONFIGURACIÓN DE LOGS
# ============================================
logging.level.com.minimarket.mscatalogo=DEBUG
logging.level.org.springframework.web=INFO
logging.level.org.hibernate.SQL=DEBUG
